### ISSUE TITLE
无变量替换部署出错

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/wecube-plugins-saltstack#130]
**描述您遇到的bug**  
部署一个应用包，无变量替换时报错：
![image](https://user-images.githubusercontent.com/43606056/77382457-6d66ff80-6dbb-11ea-9613-d2ca7a838298.png)

![image](https://user-images.githubusercontent.com/43606056/77382472-76f06780-6dbb-11ea-8f2d-2354a4e1e433.png)

**Comment by TylerTang06** [comment]
done
