### ISSUE TITLE
变量替换解析问题

### ISSUE THREAD

**Issue by jordanzhangsz** [WeBankPartners/wecube-plugins-saltstack#148]
**描述您遇到的bug**  
变量替换不该把如下的信息解析出来：
![image](https://user-images.githubusercontent.com/43606056/80076538-edc97d80-857e-11ea-8b76-fb03184fb7a8.png)

![image](https://user-images.githubusercontent.com/43606056/80076472-d4283600-857e-11ea-8aba-34462fcd949c.png)

**如何重现** 
再现行为的步骤

**预期行为** 
对你预期会发生的事情的清晰而简洁的描述。 

**截图**  
请添加屏幕截图以帮助解释您的问题。 

**附加**  
在此添加有关问题的任何其他上下文。

**Comment by TylerTang06** [comment]
done
