### ISSUE TITLE
兼容AOMP的密码加密功能

### ISSUE THREAD

**Issue by nertonsong** [WeBankPartners/wecube-plugins-saltstack#55]
WeCube需要支持加密工具，使用场景如下说明：

1. 生成两对RSA的秘钥，一对是应用方生成（app_pri.pem, app_pub.pem），另一对是由WeCube生成（sys_pri.pem, sys_pub.pem），双方都会把各自的公钥通过某种方式给到对方（WeCube提供地方可以下载公钥、应用方可以在发布时上传公钥，或者在应用包中配置公钥路径）。

2. 应用方执行发布时，WeCube用应用方的公钥app_pub.pem对明文密码内容做一次加密，之后再用自身的私钥sys_pri.pem做二次加密，这样二次加密后的密文就会被发布到生产或测试环境了。

3. 应用方程序在执行时，会取到步骤2中二次加密后的密文，使用WeCube的公钥sys_pub.pem对其进行一次解密，如果解密成功，说明密文来自WeCube。拿到解密成功后的一次加密密文后，使用应用方自身的私钥app_pri.pem（建议这个秘钥hard code在应用程序中），对其进行解密获得明文内容，做下一步操作。

加密java代码示例：
![image](https://user-images.githubusercontent.com/14288907/69934701-a8dc7600-150d-11ea-9209-4dd630ce3922.png)
![image](https://user-images.githubusercontent.com/14288907/69934728-c578ae00-150d-11ea-9ced-9d6657a5ad9b.png)

**Comment by brankbao** [comment]
多敏感数据输入，cmdb多个guid输入的格式变化，需要重新修改代码
