### ISSUE TITLE
file copy 插件解压时同名文件夹及文件未被替换

### ISSUE THREAD

**Issue by yolanda0209** [WeBankPartners/wecube-plugins-saltstack#70]
**描述您遇到的bug**  
file copy 插件解压时同名文件夹及文件未被替换：主机已存在文件夹demo_jar_v1.4，再次执行文件拷贝，原文件夹demo_jar_v1.4未被新包替换。

![image](https://user-images.githubusercontent.com/17095701/70489826-b8744400-1b37-11ea-89bc-52008035b0ca.png)

**如何重现** 
再现行为的步骤

**预期行为** 
对你预期会发生的事情的清晰而简洁的描述。 

**截图**  
请添加屏幕截图以帮助解释您的问题。 

**附加**  
在此添加有关问题的任何其他上下文。

**Comment by TylerTang06** [comment]
saltsatck 对应命令有指定参数 是否需要覆盖，先弄清楚有没有需要覆盖的需求，再做相应的调整
